export const JOB_TITLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Engineering Manager",
  "Product Manager",
  "Senior Product Manager",
  "Data Analyst",
  "Senior Data Analyst",
  "Data Scientist",
  "ML Engineer",
  "DevOps Engineer",
  "SRE Engineer",
  "QA Engineer",
  "UX Designer",
  "Senior UX Designer",
  "UI Designer",
  "Product Designer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "Cloud Architect",
  "Security Engineer",
  "Database Administrator",
  "Business Analyst",
  "Scrum Master",
  "HR Manager",
  "Finance Analyst",
  "Sales Engineer",
  "Account Executive",
  "Marketing Manager",
  "Operations Manager",
  "Customer Success Manager",
  "Technical Writer",
];

export const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Data & Analytics",
  "Design",
  "DevOps",
  "Quality Assurance",
  "Security",
  "Infrastructure",
  "Mobile",
  "Human Resources",
  "Finance",
  "Sales",
  "Marketing",
  "Operations",
  "Customer Success",
  "Legal",
  "IT Support",
];

export const COUNTRIES = [
  {
    name: "United States",
    currency: "USD",
    range: [60000, 180000] as [number, number],
  },
  {
    name: "United Kingdom",
    currency: "GBP",
    range: [40000, 130000] as [number, number],
  },
  {
    name: "India",
    currency: "INR",
    range: [600000, 3000000] as [number, number],
  },
  {
    name: "Germany",
    currency: "EUR",
    range: [45000, 120000] as [number, number],
  },
  {
    name: "Canada",
    currency: "CAD",
    range: [55000, 150000] as [number, number],
  },
  {
    name: "Australia",
    currency: "AUD",
    range: [65000, 160000] as [number, number],
  },
  {
    name: "France",
    currency: "EUR",
    range: [38000, 110000] as [number, number],
  },
  {
    name: "Netherlands",
    currency: "EUR",
    range: [42000, 115000] as [number, number],
  },
  {
    name: "Singapore",
    currency: "SGD",
    range: [60000, 160000] as [number, number],
  },
  {
    name: "Brazil",
    currency: "BRL",
    range: [60000, 300000] as [number, number],
  },
];
