export const JOB_TITLES = [
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Engineer",
  "Principal Engineer",
  "Engineering Manager",
  "Product Manager",
  "Senior Product Manager",
  "Data Analyst",
  "Senior Data Analyst",
  "Data Scientist",
  "ML Engineer",
  "DevOps Engineer",
  "SRE Engineer",
  "QA Engineer",
  "UX Designer",
  "Senior UX Designer",
  "UI Designer",
  "Product Designer",
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "Cloud Architect",
  "Security Engineer",
  "Database Administrator",
  "Systems Analyst",
  "Business Analyst",
  "Scrum Master",
  "Technical Writer",
  "HR Manager",
  "HR Business Partner",
  "Recruiter",
  "Finance Analyst",
  "Accountant",
  "Sales Engineer",
  "Account Executive",
  "Marketing Manager",
  "Content Strategist",
  "Operations Manager",
  "Customer Success Manager",
];

export const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Data & Analytics",
  "Design",
  "DevOps",
  "Quality Assurance",
  "Security",
  "Infrastructure",
  "Mobile",
  "Human Resources",
  "Finance",
  "Sales",
  "Marketing",
  "Operations",
  "Customer Success",
  "Legal",
  "IT Support",
];

export const COUNTRIES: {
  name: string;
  currency: string;
  salaryRange: [number, number];
}[] = [
  { name: "United States", currency: "USD", salaryRange: [60000, 180000] },
  { name: "United Kingdom", currency: "GBP", salaryRange: [40000, 130000] },
  { name: "India", currency: "INR", salaryRange: [600000, 3000000] },
  { name: "Germany", currency: "EUR", salaryRange: [45000, 120000] },
  { name: "Canada", currency: "CAD", salaryRange: [55000, 150000] },
  { name: "Australia", currency: "AUD", salaryRange: [65000, 160000] },
  { name: "France", currency: "EUR", salaryRange: [38000, 110000] },
  { name: "Netherlands", currency: "EUR", salaryRange: [42000, 115000] },
  { name: "Singapore", currency: "SGD", salaryRange: [60000, 160000] },
  { name: "Brazil", currency: "BRL", salaryRange: [60000, 300000] },
  { name: "Mexico", currency: "MXN", salaryRange: [200000, 900000] },
  { name: "Japan", currency: "JPY", salaryRange: [4000000, 12000000] },
  { name: "South Korea", currency: "KRW", salaryRange: [40000000, 120000000] },
  { name: "Poland", currency: "PLN", salaryRange: [60000, 240000] },
  { name: "Portugal", currency: "EUR", salaryRange: [25000, 80000] },
  { name: "Spain", currency: "EUR", salaryRange: [28000, 90000] },
  { name: "Ireland", currency: "EUR", salaryRange: [45000, 130000] },
  { name: "Sweden", currency: "SEK", salaryRange: [400000, 1000000] },
  { name: "Switzerland", currency: "CHF", salaryRange: [80000, 200000] },
  { name: "UAE", currency: "AED", salaryRange: [120000, 450000] },
];
